# Generated by Django 3.2.16 on 2023-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='craft_categories',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Decor', 'Home Decor'), ('Textiles', 'Textiles'), ('Kids Crafts', 'Kids Crafts')], default='All Things Wool', max_length=50),
        ),
    ]
