# Generated by Django 3.2.16 on 2023-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_craft_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='craft_categories',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Decor', 'Home Decor'), ('Needlepoint', 'Needlepoint'), ('Kids Crafts', 'Kids Crafts')], default='All Things Wool', max_length=50),
        ),
    ]
