# Generated by Django 3.2.16 on 2023-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Decor', 'Home Decor'), ('Needlepoint', 'Needlepoint'), ('Kids Crafts', 'Kids Crafts')], default='All Things Wool', max_length=50, verbose_name='Choose a Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Describe your crafty creation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title of your Post'),
        ),
    ]
