# Generated by Django 3.2.16 on 2023-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopbooking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='workshop',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Decor', 'Home Decor'), ('Needlepoint', 'Needlepoint'), ('Kids Crafts', 'Kids Crafts')], default='All Things Wool', max_length=50),
        ),
    ]
