# Generated by Django 3.2.16 on 2023-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230201_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbooking',
            name='time',
            field=models.CharField(choices=[('4 - 6pm', '4 - 6pm'), ('6 - 8pm', '6 - 8 pm'), ('10 - 11:30am', '10 - 11:30am'), ('11:30am - 1pm', '11:30am - 1pm')], default='4 - 6pm', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='workshop',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Crafts', 'Home Crafts'), ('Needlepoint', 'Needlepoint'), ('Kids Crafts', 'Kids Crafts')], max_length=50),
        ),
    ]
