# Generated by Django 3.2.16 on 2023-02-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbooking',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
