# Generated by Django 3.2.16 on 2023-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_workshopbooking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbooking',
            name='day',
            field=models.DateField(null=True, verbose_name='Desired Workshop Date'),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='places',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=50, verbose_name='Number of places you wish to reserve'),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='time',
            field=models.CharField(choices=[('4 - 6pm', '4 - 6pm'), ('6 - 8pm', '6 - 8 pm'), ('10 - 11:30am', '10 - 11:30am'), ('11:30am - 1pm', '11:30am - 1pm')], default='4 - 6pm', max_length=20, verbose_name='Desired Workshop Time'),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='workshop',
            field=models.CharField(choices=[('All things Wool', 'All things Wool'), ('Quilting', 'Quilting'), ('Clothing', 'Clothing'), ('Home Crafts', 'Home Crafts'), ('Needlepoint', 'Needlepoint'), ('Kids Crafts', 'Kids Crafts')], max_length=50, verbose_name='Choose which Craft Workshop you wish to attend'),
        ),
    ]
